[6.99] maintenance build for 6.99 builds

diff --git a/renpy.app/Contents/MacOS/renpy b/renpy.app/Contents/MacOS/renpy
--- a/renpy.app/Contents/MacOS/renpy
+++ b/renpy.app/Contents/MacOS/renpy
@@ -24,33 +24,27 @@ ROOT=$(cd "$ROOT"; pwd)
 BASEFILE=$(basename "$SCRIPT" .sh)
 
 if [ -z "$RENPY_PLATFORM" ] ; then
-    RENPY_PLATFORM="$(uname -s)-$(uname -m)"
-
-    case "$RENPY_PLATFORM" in
+    case "$(uname -s)-$(uname -m)" in
         Darwin-*)
             RENPY_PLATFORM="darwin-x86_64"
             ROOT1="$ROOT/../Resources/autorun"
             ROOT2="$ROOT/../../.."
-            export DYLD_INSERT_LIBRARIES="${DYLD_INSERT_LIBRARIES:-${STEAM_DYLD_INSERT_LIBRARIES}}"
                         ;;
         *-x86_64|amd64)
             RENPY_PLATFORM="linux-x86_64"
             ROOT1="$ROOT"
             ROOT2="$ROOT"
-            ;;
+                        ;;
         *-i*86)
             RENPY_PLATFORM="linux-i686"
             ROOT1="$ROOT"
             ROOT2="$ROOT"
             ;;
-        Linux-*)
-            RENPY_PLATFORM="linux-$(uname -m)"
-            ROOT1="$ROOT"
-            ROOT2="$ROOT"
-            ;;
         *)
-            ROOT1="$ROOT"
-            ROOT2="$ROOT"
+            echo "Ren'Py could not detect that platform it's running on. Please set"
+            echo "the RENPY_PLATFORM environment variable to one of \"linux-i686\" or"
+            echo "\"linux-x86_64\", or \"darwin-x86_64\" and run this command again."
+            exit 1
             ;;
     esac
 fi
@@ -70,14 +64,9 @@ for BASE in "$ROOT" "$ROOT1" "$ROOT2"; do
 done
 
 if ! test -d "$LIB"; then
-    echo "Ren'Py platform files not found in:"
-    echo
-    echo "$ROOT/lib/$RENPY_PLATFORM"
-    echo
+    echo "Ren'Py platform files not found in any of $ROOT, $ROOT1 or $ROOT2!"
     echo "Please compile the platform files using the instructions in README.md"
     echo "or point them to an existing installation using ./after_checkout.sh <path>."
-    echo
-    echo "Alternatively, please set RENPY_PLATFORM to a different platform."
     exit 1
 fi
 
